### ISSUE TITLE
Web: skrýt v nabídkách horizontal scroll

### ISSUE THREAD

**Issue by malinajan** [kmzbrnoI/solari-control#6]
Zobrazuje se ve Firefoxu na PC Krumvíř (Windows) v laboratoři, u Honzy na Debianu 12 Firefox se nezobrazuje.

**Comment by Jorgen98** [comment]
Pravdepodobne vyriešené, bude treba otestovať

**Comment by malinajan** [comment]
Otestováno, funguje.
